#!/usr/bin/env node
import { mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { run } from "./release-lib.mjs";

const generated = join(mkdtempSync(join(tmpdir(), "watchtower-typegen-")), "worker-configuration.d.ts");
run("node", ["scripts/cf-typegen.mjs", generated]);
const normalize = (value) => value
  .replace(/Generated by Wrangler[^\n]*/u, "Generated by Wrangler")
  .replace(/mainModule: typeof import\("[^"]+\/src\/index"\)/u, 'mainModule: typeof import("./src/index")')
  .replace(/[ \t]+$/gmu, "");
if (normalize(readFileSync(generated, "utf8")) !== normalize(readFileSync("worker-configuration.d.ts", "utf8"))) {
  throw new Error("worker-configuration.d.ts is out of date. Run npm run cf-typegen.");
}
console.log("Worker configuration types are up to date.");
